server:
  port: 9002
spring:
  config:
    import: optional:configserver:http://billboard-config-server.billboard:8888
eureka:
  client:
    service-url:
      defaultZone: http://billboard-eureka-server.billboard:8761/eureka/