server:
  port: 9002
spring:
  application:
    name: billboard-ads
  profiles:
    active: production
  config:
    import: optional:configserver:http://billboard-config-server.billboard:8888
  cloud:
    config:
      username: root
      name: billboard-ads
      password: c3rb3rus