version: "1.0"

networks:
  billboard:
    name: billboard

services:
  billboard-config-server:
    container_name: billboard-config-server
    build:
      context: ./billboards-config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - billboard
  billboard-taxi-service:
    container_name: billboard-taxi-service
    build:
      context: ./billboard-taxi-webapp
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    networks:
      - billboard
  billboard-ads-service:
    container_name: billboard-ads-service
    build:
      context: ./billboard-ads-webapp
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    networks:
      - billboard
  billboard-eureka-server:
    container_name: billboard-eureka-server
    build:
      context: ./billboards-eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - billboard