version: "1.0"

services:
  billboard-taxi-service-heroku-client:
    container_name: billboard-taxi-service-heroku-client
    build:
      context: ./billboard-taxi-webapp
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
  billboard-ads-service-heroku-client:
    container_name: billboard-ads-service-heroku-client
    build:
      context: ./billboard-ads-webapp
      dockerfile: Dockerfile
    ports:
      - "9004:9004"