server:
  port: 9001
spring:
  application:
    name: billboard-taxi
  profiles:
    active: production
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: root
      name: billboard-taxi
      password: c3rb3rus