spring:
  application:
    name: billboard-taxi
  cloud:
    config:
      username: root
      name: billboard-taxi
      password: c3rb3rus
      fail-fast: true
      retry:
        max-attempts: 100