server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dmitriydb/learning-spring-cloud-config-billboards
  security:
    user:
      name: root
      password: c3rb3rus
  application:
    name: billboards-config-server
eureka:
  client:
    service-url:
      defaultZone: http://billboard-eureka-server.billboard:8761/eureka/